[package]
name = "fsevent-better"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "1.3"
core-foundation = "0.9"
futures = "0.3"
log = "0.4"
once_cell = "1.8"
pretty_env_logger = "0.4"
tokio = { version = "1.14", features = ["sync"] }
tokio-stream = "0.1"

[dev-dependencies]
libc = "0.2"
tempfile = "3.2"
tokio = { version = "1.14", features = ["rt-multi-thread", "sync", "macros"] }
