[package]
name = "fsevent-better"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3"
core-foundation = "0.9"
futures = "0.3"
log = "0.4"
pretty_env_logger = "0.4"
tokio = { version = "1.14", features = ["sync"] }
tokio-stream = "0.1"
