on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Test

jobs:
  lint:
    name: Lint
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
        name: Checkout 🛎️
      - uses: actions-rs/toolchain@v1
        name: Setup Cargo Toolchain 🛎️
        with:
          components: rustfmt, clippy
          toolchain: stable
          default: true
      - uses: extractions/setup-just@v1
      - uses: Swatinem/rust-cache@v1
      - name: Running Lints 🔨
        run: just ci

  test:
    name: Test
    runs-on: macos-11
    env:
      CI: 1
    steps:
      - uses: actions/checkout@v2
        name: Checkout 🛎️
      - uses: actions-rs/toolchain@v1
        name: Setup Cargo Toolchain 🛎️
        with:
          profile: minimal
          toolchain: stable
          default: true
      - uses: extractions/setup-just@v1
      - uses: Swatinem/rust-cache@v1
      - name: Running Tests 🚀
        run: just test-all